.

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -1,15 +1,24 @@
-if ! command -v nvim >/dev/null 2>&1; then
-    echo install neovim
-    sudo apt install -y build-essential fzf unzip sqlite3 libsqlite3-dev ripgrep
+#!/bin/bash
+
+# Save this file as ~/.config/yadm/bootstrap and make it executable. It will
+# execute all executable files (excluding templates and editor backups) in the
+# ~/.config/yadm/bootstrap.d directory when run.
+
+set -eu
+
+# Directory to look for bootstrap executables in
+BOOTSTRAP_D="${BASH_SOURCE[0]}.d"
+
+if [[ ! -d "$BOOTSTRAP_D" ]]; then
+    echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
+    exit 1
 fi
 
-if ! command -v fd >/dev/null 2>&1; then
-    echo install fd
-    sudo apt install -y fd-find
-    ln -s /usr/bin/fdfind ~/.local/bin/fd
-fi
-
-if ! command -v zsh >/dev/null 2>&1; then
-    echo install zsh
-    sudo apt install -y zsh
-fi
+find -L "$BOOTSTRAP_D" -type f | sort | while IFS= read -r bootstrap; do
+    if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
+        if ! "$bootstrap"; then
+            echo "Error: bootstrap '$bootstrap' failed" >&2
+            exit 1
+        fi
+    fi
+done
